language: cpp
dist: trusty
os: linux
sudo: required

before_script:
  - sudo apt-get install qt5-qmake

script:
  - qmake -version
  - qmake CONFIG+=release gibs.pro
  - make -j

branches:
  only:
    - master
    - dev
