language: cpp
dist: trusty
sudo: required
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

script:
  - source /opt/qt510/bin/qt510-env.sh
  - g++ --version
  - cmake --version
  - make -j `nproc`
  #- cp gibs/build/out/gibs deployment/gibs
  #- cd deployment
  #- wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  #- chmod +x linuxdeployqt-continuous-x86_64.AppImage
  #- ../scripts/deploy-linux.sh ./linuxdeployqt-continuous-x86_64.AppImage $(which qmake) gibs.desktop
  #- cd ..

branches:
  only:
    - dev
