
option(GIBS_LTO "Enable link time optimization" OFF)
option(GIBS_UNITY_BUILD "Enable unity (jumbo) builds, which offer much faster compilation times" OFF)
option(GIBS_CCACHE "Enable ccache - much faster repeating builds" OFF)
option(GIBS_MOLD "Enable mold linker - much faster linker" OFF)
option(GIBS_ASAN "Enable address sanitizer" OFF)
option(GIBS_STRICT "Treat warnings errors, plus enforce other, related checks" ON)

# Enable LTO (link time optimization)
if (GIBS_LTO)
  set(LINK_TIME_OPTIMIZATION TRUE)
  message("Building with LTO enabled")
endif ()

# Enable unity builds
if (GIBS_UNITY_BUILD)
  set(UNITY_BUILD_VALUE TRUE)
  set(UNITY_BUILD_MODE_VALUE BATCH)
  set(UNITY_BUILD_BATCH_SIZE_VALUE 16)
  message("Building with unity (jumbo) build enabled")
endif ()

if (GIBS_CCACHE)
  set(CMAKE_CXX_COMPILER_LAUNCHER ccache)
endif ()

if (GIBS_MOLD)
  # See:https://github.com/rui314/mold
  # and: https://gist.github.com/MawKKe/b8af6c1555f1c7aa4c2760350ed97fff
  set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=mold")
  set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=mold")
endif ()

if (GIBS_ASAN)
    if (WIN32)
        if (MSVC)
            message("No ASAN for you, my boy!") # But! modern MSVC does support asan!
        endif ()
    else ()
        add_definitions("-fsanitize=address" "-fno-optimize-sibling-calls" "-fsanitize-address-use-after-scope" "-fno-omit-frame-pointer")
        add_link_options("-fsanitize=address" "-fno-optimize-sibling-calls" "-fsanitize-address-use-after-scope" "-fno-omit-frame-pointer")
    endif ()
endif ()

if (WIN32)
    if (MSVC)
        if (${ENABLE_STRICT})
            set(COMPILE_OPTIONS "/utf-8" "/WX" "/wd4573" "/W3" "/bigobj")
        else()
            set(COMPILE_OPTIONS "/utf-8" "/bigobj")
        endif()
        if(${STATIC_QT})
            set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib")
            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
            list(APPEND COMPILE_OPTIONS "/MT")
        endif()
    endif()
elseif(APPLE)
    if (${ENABLE_STRICT})
        set(COMPILE_OPTIONS "-Werror" "-Wall" "-Wextra" "-Wconversion" "-Wno-error=switch")
    endif()
    if(${STATIC_QT})
        set(CMAKE_CXX_VISIBILITY_PRESET hidden)
    endif()
else()
  # "-Wsign-conversion" "-pedantic-errors"
    if (${ENABLE_EMBEDDED_BUILD})
        # pass
    else ()
        if (${ENABLE_STRICT})
            set(COMPILE_OPTIONS "-Werror" "-Wall" "-Wextra" "-Wconversion" "-Wno-error=deprecated-declarations" "-Wno-error=nonnull")
        endif()
    endif()
endif()